version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - receiver
      - websocket

  receiver:
    build: ./receiver
    ports:
      - "8005:8005"
    volumes:
      - efs_volume:/shared_volume
    environment:
      - SHARED_VOLUME_PATH=/shared_volume
      - REDIS_HOST=redis
    depends_on:
      - redis

  transcriber:
    build: ./transcriber
    volumes:
      - efs_volume:/shared_volume
    environment:
      - SHARED_VOLUME_PATH=/shared_volume
      - REDIS_HOST=redis
    deploy:
      replicas: 2  # Scale transcriber workers
    depends_on:
      - redis

  merger:
    build: ./merger
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  websocket:
    build: ./websocket
    ports:
      - "8006:8006"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  efs_volume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=your-efs-endpoint.efs.region.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
      device: ":/" 